const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM '+Number(n||0).toFixed(2);
const time=t=>new Date(t).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur',hour12:false});
const methods={cash:'现金',duitnow:'DuitNow',foodcourt:'食阁',card:'刷卡',bank_transfer:'转账',other:'其他'};
const rpc=async(db,name,args)=>{const r=await db.rpc(name,args);if(r.error)throw Error(r.error.message);return r.data;};

function statementMarkup(report){
 const s=report?.stats||{},items=report?.items||[],payments=report?.methods||[];
 const sold=items.length?items.map(i=>`<div class="statement-item"><div><strong>${esc(i.item_name||'未命名商品')}</strong><small>${Number(i.quantity||0)} 杯</small></div><span>${money(i.gross_rm)}</span><span class="statement-discount">−${money(i.discount_rm)}</span><b>${money(i.net_rm)}</b></div>`).join(''):'<p class="field-note statement-empty">本营业日还没有已结账商品。</p>';
 const paid=payments.length?payments.map(m=>`<div><span>${esc(methods[m.method]||m.method)}</span><strong>${money(m.net_rm)}</strong></div>`).join(''):'<p class="field-note">本营业日暂无收款。</p>';
 return `<section class="daily-statement"><div class="statement-heading"><div><p class="kicker">DAILY STATEMENT</p><h2>${esc(report?.day||'营业日报')}</h2></div><span class="statement-period">${report?.start_at?time(report.start_at):''}<br>${report?.end_at?'至 '+time(report.end_at):''}</span></div><div class="report-stats statement-stats"><article class="report-stat highlight"><span>实收净额</span><strong>${money(s.net_rm)}</strong><small>${Number(s.orders||0)} 张收款单</small></article><article class="report-stat"><span>售出</span><strong>${Number(s.units||0)} 杯</strong><small>${items.length} 种商品</small></article><article class="report-stat"><span>优惠</span><strong>−${money(s.discount_rm)}</strong><small>原价 ${money(s.gross_rm)}</small></article><article class="report-stat"><span>退款／退回</span><strong>${money(s.refunded_rm)}</strong><small>${Number(s.cancelled_orders||0)} 张取消单</small></article></div><div class="statement-section"><div class="statement-section-head"><h3>商品销量</h3><span>商品 · 数量 · 原价 · 优惠 · 净额</span></div><div class="statement-items">${sold}</div></div><div class="statement-section"><div class="statement-section-head"><h3>收款方式</h3><span>${Number(s.payment_orders||s.orders||0)} 张涉及款项的订单</span></div><div class="day-methods">${paid}</div></div><div class="statement-foot"><span>待完成款项 <strong>${Number(report?.pending_count||0)}</strong> 张</span><span>超过 3 天 <strong>${Number(report?.blocker_count||0)}</strong> 张</span></div></section>`;
}

export function createDayClose({db,root,isOwner,notice,onOrdersChanged,onOwnerEdit}){
 let data=null,statement=null,epoch=0,pendingRequest=null,working=false;
 root.innerHTML=`<form data-dc="range" class="report-range"><label>营业日<input data-dc="day" type="date" required></label><button type="submit">查看</button><button data-dc="today" type="button">今天</button></form><p data-dc="status" class="field-note" role="status"></p><div data-dc="summary"></div><div data-dc="pending"></div><form data-dc="close" class="card stack statement-close"><div><p class="kicker">CLOSING</p><h3>Daily Statement</h3></div><label>备注（选填）<textarea data-dc="notes" rows="2" maxlength="600"></textarea></label><label class="checkline"><input data-dc="confirmed" type="checkbox" required>已核对日报</label><button data-dc="submit" type="submit" class="primary">完成 Closing</button></form><section data-dc="closed" class="card hidden"></section><section data-dc="resolve" class="card hidden"></section><details data-dc="settings" class="card hidden"><summary>营业日截止设置</summary><form data-dc="cutoffForm" class="stack"><label>隔天截止时间<input data-dc="cutoff" type="time" required></label><p data-dc="cutoffNote" class="field-note"></p><button type="submit">保存</button></form></details>`;
 const $=key=>root.querySelector('[data-dc="'+key+'"]');
 function render(d){
  data=d;pendingRequest=null;const c=d.context,closed=d.closing?.state==='closed';statement=closed&&d.closing?.snapshot?.stats?d.closing.snapshot:d;
  $('day').value=d.day;$('status').textContent=`${d.day} 营业日 · ${time(d.start_at)} 至 ${time(d.end_at)}${d.closing?.state==='reopened'?' · 有新款项，需重新生成日报':''}`;
  $('summary').innerHTML=statementMarkup(statement);
  $('pending').innerHTML=d.pending_count?`<details class="card day-pending" ${d.blocker_count?'open':''}><summary>${d.pending_count} 张未完成款项${d.blocker_count?' · '+d.blocker_count+' 张超过 3 天，禁止 Closing':' · 可备注后完成 Closing'}</summary>${d.pending.map(o=>`<div class="day-pending-row"><div><strong>${esc(o.order_no||'未编号')} · ${esc(o.table_label||'Walk-in')}</strong><small>${time(o.created_at)} · ${money(o.amount_rm)}${o.overdue?' · 需 Owner 处理':''}</small></div>${isOwner()?`<button type="button" data-resolve-order="${esc(o.id)}">处理</button>`:''}</div>`).join('')}${d.pending_count>100?'<p>仅显示最早100张，处理后刷新继续。</p>':''}</details>`:'';
  $('close').classList.toggle('hidden',closed);$('closed').classList.toggle('hidden',!closed);$('submit').disabled=working||d.blocker_count>0;
  if(closed){const x=d.closing;$('closed').innerHTML=`<div class="statement-closed-head"><div><p class="kicker">CLOSING COMPLETE</p><h3>Daily Statement 已保存 · 第${x.revision}版</h3><p class="field-note">${time(x.closed_at)}${x.notes?' · '+esc(x.notes):''}</p></div><button type="button" data-print-day class="primary">打印 / 保存 PDF</button></div>${isOwner()?'<label>重新打开原因<input data-reopen-reason maxlength="300" placeholder="必填"></label><button type="button" data-reopen-day>重新打开 Closing</button>':''}`;}
  $('settings').classList.toggle('hidden',!isOwner());const minutes=c.next?.cutoff_minutes??c.cutoff_minutes;$('cutoff').value=String(Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');$('cutoffNote').textContent=c.next?'生效日：'+c.next.effective_day:'马来西亚时间';
 }
 async function load(day){const ticket=++epoch;$('status').textContent='正在整理 Daily Statement…';try{const d=await rpc(db,'yt_pos_day_preview',{p_day:day||null});if(ticket!==epoch)return;render(d);}catch(e){if(ticket===epoch){data=null;statement=null;$('submit').disabled=true;$('status').textContent='加载失败，请重新查看。';notice(e.message,true);}}}
 async function run(button,fn){if(working)return;working=true;button.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{working=false;button.disabled=false;if(data)$('submit').disabled=data.blocker_count>0;}}
 function printStatement(){
  if(!data||!statement)return;const title=`Yetipsy Daily Statement · ${data.day}`,popup=window.open('','yt-daily-statement','width=900,height=760');if(!popup){notice('浏览器阻止了打印窗口，请允许弹出窗口后重试',true);return;}
  popup.document.open();popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>body{font:14px/1.5 Arial,sans-serif;color:#1e2922;margin:32px}.kicker{font-size:11px;letter-spacing:.12em;color:#775d2e}.statement-heading,.statement-section-head,.statement-closed-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.statement-period{font-size:12px;text-align:right}.report-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.report-stat,.statement-section{border:1px solid #cad1ca;border-radius:12px;padding:14px}.report-stat span,.report-stat small{display:block;color:#5d695f}.report-stat strong{display:block;font-size:22px;margin:5px 0}.statement-section{margin:12px 0}.statement-section h3{margin:0}.statement-section-head span{font-size:11px;color:#6b766d}.statement-item{display:grid;grid-template-columns:minmax(180px,1fr) 100px 100px 100px;gap:12px;padding:10px 0;border-bottom:1px solid #e4e7e3;text-align:right}.statement-item>div{text-align:left}.statement-item small{display:block;color:#667168}.statement-discount{color:#9b493e}.day-methods>div,.statement-foot{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #e4e7e3}.statement-foot{margin-top:12px;border:0}.field-note{color:#68736b}@media(max-width:650px){.report-stats{grid-template-columns:1fr 1fr}.statement-item{grid-template-columns:1fr 70px}.statement-item span{display:none}}@media print{body{margin:12mm}}</style></head><body><header class="statement-closed-head"><div><p class="kicker">YE·TIPSY · KLUANG</p><h1>${esc(title)}</h1></div><strong>CLOSING #${Number(data.closing?.revision||1)}</strong></header>${statementMarkup(statement)}${data.closing?.notes?`<p><strong>备注：</strong>${esc(data.closing.notes)}</p>`:''}</body></html>`);popup.document.close();popup.focus();setTimeout(()=>popup.print(),120);
 }
 $('range').onsubmit=e=>{e.preventDefault();if(!working)load($('day').value);};$('today').onclick=()=>{if(!working)load();};$('notes').oninput=()=>pendingRequest=null;
 $('close').onsubmit=e=>{e.preventDefault();run($('submit'),async()=>{if(!data)throw Error('先刷新 Daily Statement');if(data.pending_count&&!confirm(`还有 ${data.pending_count} 张未完成款项订单，将继续保留待结。确认完成 Closing？`))return;
  pendingRequest||={p_day:data.day,p_notes:$('notes').value.trim(),p_request:crypto.randomUUID(),p_fingerprint:data.fingerprint};
  try{await rpc(db,'yt_pos_day_statement_close',pendingRequest);}catch(e){if(e.message!=='Failed to fetch')pendingRequest=null;throw e;}
  notice('Daily Statement 已生成，营业日已完成 Closing');await load(data.day);
 });};
 $('cutoffForm').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const [h,m]=$('cutoff').value.split(':').map(Number);await rpc(db,'yt_business_cutoff_save',{p_minutes:h*60+m});notice('截止时间已保存，下一营业日起生效');await load(data?.day);});};
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-print-day'))printStatement();
  if(b.hasAttribute('data-reopen-day'))run(b,async()=>{const reason=root.querySelector('[data-reopen-reason]').value.trim();await rpc(db,'yt_pos_day_reopen',{p_day:data.day,p_reason:reason});await load(data.day);});
  if(b.dataset.resolveOrder&&isOwner()){const o=data.pending.find(x=>x.id===b.dataset.resolveOrder);if(!o)return;if(o.payment_status==='paid'){onOwnerEdit?.(o.id);return;}$('resolve').classList.remove('hidden');$('resolve').innerHTML=`<h3>Owner 处理 · ${esc(o.order_no||'未编号')}</h3><form data-resolve-form class="stack"><label>处理方式<select name="action"><option value="complete">确认真实收款并完成订单</option><option value="cancel">取消订单，释放未使用奖励</option></select></label><label>收款方式<select name="method">${Object.entries(methods).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>批准原因<textarea name="reason" required minlength="2" maxlength="300"></textarea></label><label class="checkline"><input type="checkbox" required>已核对订单；完成订单表示实际已收到款项</label><button type="submit" class="primary">批准并执行</button><button type="button" data-resolve-close>返回</button></form>`;
   $('resolve').scrollIntoView({block:'nearest'});$('resolve').querySelector('form').onsubmit=ev=>{ev.preventDefault();const f=ev.currentTarget;run(ev.submitter,async()=>{await rpc(db,'yt_pos_aged_resolve',{p_order:o.id,p_action:f.elements.action.value,p_reason:f.elements.reason.value.trim(),p_method:f.elements.method.value});$('resolve').classList.add('hidden');await load(data.day);await onOrdersChanged?.();notice('Owner 已处理订单');});};
  }if(b.hasAttribute('data-resolve-close'))$('resolve').classList.add('hidden');
 });
 return {load,cancel(){epoch++;},clear(){epoch++;data=null;statement=null;pendingRequest=null;root.querySelectorAll('input,textarea').forEach(x=>{if(x.type==='checkbox')x.checked=false;else x.value='';});for(const key of ['summary','pending','closed','resolve'])$(key).replaceChildren();$('submit').disabled=true;}};
}
