const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM '+Number(n||0).toFixed(2);
const time=t=>new Date(t).toLocaleString('zh-CN',{timeZone:'Asia/Kuala_Lumpur',hour12:false});
const methods={cash:'现金',duitnow:'DuitNow',foodcourt:'食阁',card:'刷卡',bank_transfer:'转账',other:'其他'};
const rpc=async(db,name,args)=>{const r=await db.rpc(name,args);if(r.error)throw Error(r.error.message);return r.data;};
export function createDayClose({db,root,isOwner,notice,onOrdersChanged,onOwnerEdit}){
 let data=null,epoch=0,pendingRequest=null,working=false;
 root.innerHTML=`<form data-dc="range" class="report-range"><label>营业日<input data-dc="day" type="date" required></label><button type="submit">查看</button><button data-dc="today" type="button">今天</button></form><p data-dc="status" class="field-note" role="status"></p><div data-dc="summary"></div><div data-dc="pending"></div><form data-dc="close" class="card stack"><h3>现金盘点</h3><div class="pair"><label>开档备用金 RM<input data-dc="opening" type="number" min="0" max="1000000" step="0.01" value="0" required></label><label>取出／支出现金 RM<input data-dc="out" type="number" min="0" max="1000000" step="0.01" value="0" required></label></div><p data-dc="expected" class="day-close-total"></p><label>实际现金 RM<input data-dc="actual" type="number" min="0" max="1000000" step="0.01" required></label><label>日结备注<textarea data-dc="notes" rows="2" maxlength="600" placeholder="有未完成款项的订单、现金差额或取出现金时需填写"></textarea></label><label class="checkline"><input data-dc="confirmed" type="checkbox" required>已核对收款与实际现金</label><button data-dc="submit" type="submit" class="primary">确认日结</button></form><section data-dc="closed" class="card hidden"></section><section data-dc="resolve" class="card hidden"></section><details data-dc="settings" class="card hidden"><summary>营业日截止设置</summary><form data-dc="cutoffForm" class="stack"><label>隔天截止时间<input data-dc="cutoff" type="time" required></label><p data-dc="cutoffNote" class="field-note"></p><button type="submit">保存 · 下一营业日起生效</button></form></details>`;
 const $=key=>root.querySelector('[data-dc="'+key+'"]');
 function calc(){if(!data)return;const expected=Number($('opening').value||0)+Number(data.stats.cash_rm)-Number($('out').value||0);$('expected').textContent='应有现金 '+money(expected)+($('actual').value!==''?' · 差额 '+money(Number($('actual').value)-expected):'');}
 function render(d){data=d;pendingRequest=null;$('day').value=d.day;const c=d.context,closed=d.closing?.state==='closed';
  $('status').textContent=`${d.day} 营业日 · ${time(d.start_at)} 至 ${time(d.end_at)}${d.closing?.state==='reopened'?' · 需重新日结':''}`;
  $('summary').innerHTML=`<div class="report-stats"><article class="report-stat highlight"><span>实收净额</span><strong>${money(d.stats.net_rm)}</strong><small>${d.stats.orders} 张收款单</small></article><article class="report-stat"><span>现金净额</span><strong>${money(d.stats.cash_rm)}</strong></article><article class="report-stat"><span>退款／退回</span><strong>${money(d.stats.refunded_rm)}</strong></article></div><div class="day-methods">${d.methods.map(m=>`<div><span>${esc(methods[m.method]||m.method)}</span><strong>${money(m.net_rm)}</strong></div>`).join('')||'<p class="field-note">本营业日暂无收款。</p>'}</div>`;
  $('pending').innerHTML=d.pending_count?`<details class="card day-pending" ${d.blocker_count?'open':''}><summary>${d.pending_count} 张未完成款项${d.blocker_count?' · '+d.blocker_count+' 张超过72小时，禁止日结':' · 确认后可继续日结'}</summary>${d.pending.map(o=>`<div class="day-pending-row"><div><strong>${esc(o.order_no||'未编号')} · ${esc(o.table_label||'Walk-in')}</strong><small>${time(o.created_at)} · ${money(o.amount_rm)}${o.overdue?' · 需 Owner 处理':''}</small></div>${isOwner()?`<button type="button" data-resolve-order="${esc(o.id)}">处理</button>`:''}</div>`).join('')}${d.pending_count>100?'<p>仅显示最早100张，处理后刷新继续。</p>':''}</details>`:'';
  $('close').classList.toggle('hidden',closed);$('closed').classList.toggle('hidden',!closed);$('submit').disabled=working||d.blocker_count>0;
  if(closed){const x=d.closing;$('closed').innerHTML=`<h3>已完成日结 · 第${x.revision}版</h3><p>应有 ${money(x.expected_cash)} · 实际 ${money(x.actual_cash)} · 差额 ${money(x.difference_rm)}</p><p class="field-note">${time(x.closed_at)}${x.notes?' · '+esc(x.notes):''}</p>${isOwner()?'<label>重新打开原因<input data-reopen-reason maxlength="300" placeholder="必填"></label><button type="button" data-reopen-day>重新打开日结</button>':''}`;}
  $('settings').classList.toggle('hidden',!isOwner());const minutes=c.next?.cutoff_minutes??c.cutoff_minutes;$('cutoff').value=String(Math.floor(minutes/60)).padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');$('cutoffNote').textContent=c.next?'已设置：'+c.next.effective_day+' 起生效。':'使用马来西亚时间；历史营业日保持原截止设置。';calc();
 }
 async function load(day){const ticket=++epoch;$('status').textContent='正在读取日结…';try{const d=await rpc(db,'yt_pos_day_preview',{p_day:day||null});if(ticket!==epoch)return;render(d);}catch(e){if(ticket===epoch){data=null;$('submit').disabled=true;$('status').textContent='加载失败，请重新查看。';notice(e.message,true);}}}
 async function run(button,fn){if(working)return;working=true;button.disabled=true;try{await fn();}catch(e){notice(e.message,true);}finally{working=false;button.disabled=false;if(data)$('submit').disabled=data.blocker_count>0;}}
 $('range').onsubmit=e=>{e.preventDefault();if(!working)load($('day').value);};$('today').onclick=()=>{if(!working)load();};
 for(const key of ['opening','out','actual'])$(key).oninput=()=>{pendingRequest=null;calc();};$('notes').oninput=()=>pendingRequest=null;
 $('close').onsubmit=e=>{e.preventDefault();run($('submit'),async()=>{if(!data)throw Error('先刷新日结');if(data.pending_count&&!confirm(`还有 ${data.pending_count} 张未完成款项订单，将继续保留待结。确认完成日结？`))return;
  pendingRequest||={p_day:data.day,p_opening:Number($('opening').value),p_cash_out:Number($('out').value),p_actual:Number($('actual').value),p_notes:$('notes').value.trim(),p_request:crypto.randomUUID(),p_fingerprint:data.fingerprint};
  try{await rpc(db,'yt_pos_day_close',pendingRequest);}catch(e){if(e.message!=='Failed to fetch')pendingRequest=null;throw e;}
  notice('日结已保存');await load(data.day);
 });};
 $('cutoffForm').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const [h,m]=$('cutoff').value.split(':').map(Number);await rpc(db,'yt_business_cutoff_save',{p_minutes:h*60+m});notice('截止时间已保存，下一营业日起生效');await load(data?.day);});};
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.hasAttribute('data-reopen-day'))run(b,async()=>{const reason=root.querySelector('[data-reopen-reason]').value.trim();await rpc(db,'yt_pos_day_reopen',{p_day:data.day,p_reason:reason});await load(data.day);});
  if(b.dataset.resolveOrder&&isOwner()){const o=data.pending.find(x=>x.id===b.dataset.resolveOrder);if(!o)return;if(o.payment_status==='paid'){onOwnerEdit?.(o.id);return;}$('resolve').classList.remove('hidden');$('resolve').innerHTML=`<h3>Owner 处理 · ${esc(o.order_no||'未编号')}</h3><form data-resolve-form class="stack"><label>处理方式<select name="action"><option value="complete">确认真实收款并完成订单</option><option value="cancel">取消订单，释放未使用奖励</option></select></label><label>收款方式<select name="method">${Object.entries(methods).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>批准原因<textarea name="reason" required minlength="2" maxlength="300"></textarea></label><label class="checkline"><input type="checkbox" required>已核对订单；完成订单表示实际已收到款项</label><button type="submit" class="primary">批准并执行</button><button type="button" data-resolve-close>返回</button></form>`;
   $('resolve').scrollIntoView({block:'nearest'});$('resolve').querySelector('form').onsubmit=ev=>{ev.preventDefault();const f=ev.currentTarget;run(ev.submitter,async()=>{await rpc(db,'yt_pos_aged_resolve',{p_order:o.id,p_action:f.elements.action.value,p_reason:f.elements.reason.value.trim(),p_method:f.elements.method.value});$('resolve').classList.add('hidden');await load(data.day);await onOrdersChanged?.();notice('Owner 已处理订单');});};
  }if(b.hasAttribute('data-resolve-close'))$('resolve').classList.add('hidden');
 });
 return {load,cancel(){epoch++;},clear(){epoch++;data=null;pendingRequest=null;root.querySelectorAll('input,textarea').forEach(x=>{if(x.type==='checkbox')x.checked=false;else x.value='';});for(const key of ['summary','pending','closed','resolve'])$(key).replaceChildren();$('submit').disabled=true;}};
}
