const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createPointsAdmin({db,root,isOwner,notice}){
 let data=null,epoch=0,tab='games',pending=null;
 const read=r=>{if(r.error)throw r.error;return r.data;};
 const options=(list,selected)=>list.map(r=>`<option value="${esc(r.id)}" ${r.id===selected?'selected':''}>${esc(r.name)}</option>`).join('');
 async function load(){if(!isOwner())return;const ticket=++epoch;const result=read(await db.rpc('yt_owner_points_settings'));if(!isOwner()||ticket!==epoch)return;data=result;if(!pending)try{pending=JSON.parse(sessionStorage.getItem('yt-owner-shop:'+data.actor_id)||'null');}catch{}render();}
 async function save(kind,payload,button){if(!isOwner())return;const original=button.textContent;button.disabled=true;try{read(await db.rpc('yt_owner_points_save',{p_kind:kind,p_data:payload}));pending=null;sessionStorage.removeItem('yt-owner-shop:'+data.actor_id);await load();notice('已保存；新规则从下一局或下次兑换生效');}catch(e){if(['P0001','23514','23503','22P02','22007','22008'].includes(e.code)){pending=null;sessionStorage.removeItem('yt-owner-shop:'+data.actor_id);root.querySelectorAll('input,select').forEach(el=>el.disabled=false);}button.textContent='重试保存';notice(({invalid_points_settings:'请核对积分上限与计分范围',reward_not_pos_bound:'请先为奖励绑定可核销权益',stock_below_used:'总库存不能少于已兑换数量',request_conflict:'保存请求不一致，请重新打开设置'})[e.message]||(['23514','22007','22008'].includes(e.code)?'请核对数值与日期，结束时间必须晚于开始时间':e.message||'连接中断，请重试保存'),true);throw e;}finally{button.disabled=false;if(button.textContent!=='重试保存')button.textContent=original;}}
 function render(){
  root.innerHTML='<nav class="tool-subtabs points-admin-tabs">'+[['games','技巧积分'],['reward','奖励等值'],['shop','积分商场']].map(([key,name])=>`<button type="button" data-point-tab="${key}" class="${tab===key?'active':''}">${name}</button>`).join('')+'</nav><div id="pointAdminContent"></div>';
  root.querySelectorAll('[data-point-tab]').forEach(b=>b.onclick=()=>{if(pending){notice('请先重试保存上一笔设置',true);return;}tab=b.dataset.pointTab;render();});
  const box=root.querySelector('#pointAdminContent');
  if(tab==='games'){
   box.innerHTML='<p class="muted">三回合取最佳成绩。100% 领取 MAX；每局开场即保存计分规则。</p>'+data.games.map(g=>`<form class="card stack" data-point-game="${esc(g.id)}"><h3>${esc(g.title)}</h3><label>积分 MAX<input name="max" type="number" min="1" max="1000000" required value="${Number(g.points_max)}"></label>${g.slug==='reaction-test'?`<div class="pair"><label>100%：反应 ≤ ms<input name="perfect" type="number" min="1" max="8999" required value="${g.perfect_ms}"></label><label>0%：反应 ≥ ms<input name="zero" type="number" min="2" max="9000" required value="${g.zero_ms}"></label></div><p class="muted tiny">两者之间按比例计分，系统与顾客显示一致。</p>`:'<p class="muted tiny">最佳精准度就是本局达成率。</p>'}<button type="submit" class="main-button">保存这款游戏</button></form>`).join('')+`<form id="pointExpiryForm" class="card stack"><label>积分有效天数<input name="days" type="number" min="0" max="3650" required value="${data.validity_days}"></label><p class="muted tiny">0 为不设到期。只影响新开局，现有积分保持原有效期。</p><button class="main-button" type="submit">保存有效期</button></form>`;
   box.querySelectorAll('[data-point-game]').forEach(form=>form.onsubmit=e=>{e.preventDefault();const g=data.games.find(x=>x.id===form.dataset.pointGame),f=form.elements;save('game',{id:g.id,points_max:Number(f.max.value),perfect_ms:Number(f.perfect?.value||g.perfect_ms),zero_ms:Number(f.zero?.value||g.zero_ms)},form.querySelector('button')).catch(()=>{});});
   box.querySelector('#pointExpiryForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;save('expiry',{days:Number(form.elements.days.value)},form.querySelector('button')).catch(()=>{});};
  }else if(tab==='reward'){
   box.innerHTML=`<form id="rewardPointForm" class="card stack"><h3>游戏奖品等值积分</h3><p class="muted tiny">只在运气游戏结束时二选一；已领入钱包的奖励不能再转换。</p><label>奖励<select name="reward" required>${options(data.rewards)}</select></label><label>等值积分<input name="points" type="number" min="1" max="1000000" placeholder="留空则只能领取奖品"></label><button class="main-button" type="submit">保存等值积分</button></form>`;
   const form=box.querySelector('form');function choose(){form.elements.points.value=data.rewards.find(x=>x.id===form.elements.reward.value)?.points||'';}form.elements.reward.onchange=choose;choose();form.onsubmit=e=>{e.preventDefault();save('reward',{id:form.elements.reward.value,points:form.elements.points.value?Number(form.elements.points.value):null},form.querySelector('button')).catch(()=>{});};
  }else renderShop(box);
 }
 function renderShop(box){
  box.innerHTML='<div class="points-admin-list">'+data.items.map(i=>`<button type="button" data-point-item="${esc(i.id)}"><strong>${esc(i.name)} · ${i.points_cost} P</strong><small>${i.active?'上架':'下架'} · 已兑 ${i.stock_used}${i.stock_limit!=null?' / '+i.stock_limit:''}</small></button>`).join('')+'</div><button id="pointNewItem" type="button" class="quiet">＋ 新增兑换项目</button><div id="pointItemForm"></div>';
  box.querySelectorAll('[data-point-item]').forEach(b=>b.onclick=()=>{if(pending)return notice('请重试保存上一笔设置',true);edit(data.items.find(x=>x.id===b.dataset.pointItem));});box.querySelector('#pointNewItem').onclick=()=>{if(pending)return notice('请重试保存上一笔设置',true);edit();};edit();
  function edit(i={}){if(pending)i={id:pending.id,reward_id:pending.reward,points_cost:pending.cost,per_member_limit:pending.member_limit,stock_limit:pending.stock,sort_order:pending.sort,starts_at:pending.starts_at,ends_at:pending.ends_at,active:pending.active};
   const target=box.querySelector('#pointItemForm');target.innerHTML=`<form class="card stack"><h3>${i.id?'编辑':'新增'}兑换项目</h3><label>已绑定权益的奖励<select name="reward" required><option value="">请选择</option>${options(data.rewards.filter(x=>x.bound),i.reward_id)}</select></label><div class="pair"><label>兑换积分<input name="cost" type="number" min="1" max="1000000" required value="${i.points_cost||''}"></label><label>每人限额<input name="member" type="number" min="1" placeholder="不限" value="${i.per_member_limit||''}"></label></div><div class="pair"><label>总库存<input name="stock" type="number" min="${i.stock_used||0}" placeholder="不限" value="${i.stock_limit??''}"></label><label>排序<input name="sort" type="number" min="0" max="100000" required value="${i.sort_order??100}"></label></div><details><summary>上架日期（选填）</summary><div class="pair"><label>开始<input name="starts" type="datetime-local"></label><label>结束<input name="ends" type="datetime-local"></label></div></details><label class="checkline"><input name="active" type="checkbox" ${i.active?'checked':''}>上架到客户端</label><p class="muted tiny">沿用奖励有效期和核销规则；总库存包含已兑换数量。</p><button class="main-button" type="submit">保存兑换项目</button></form>`;
   const form=target.querySelector('form');for(const [field,value]of [['starts',i.starts_at],['ends',i.ends_at]])if(value){const d=new Date(value);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());form.elements[field].value=d.toISOString().slice(0,16);}
   form.onsubmit=e=>{e.preventDefault();const f=form.elements;pending||={id:i.id||null,reward:f.reward.value,cost:Number(f.cost.value),stock:f.stock.value?Number(f.stock.value):null,member_limit:f.member.value?Number(f.member.value):null,sort:Number(f.sort.value),starts_at:f.starts.value?new Date(f.starts.value).toISOString():null,ends_at:f.ends.value?new Date(f.ends.value).toISOString():null,active:f.active.checked,request:crypto.randomUUID()};sessionStorage.setItem('yt-owner-shop:'+data.actor_id,JSON.stringify(pending));for(const el of form.querySelectorAll('input,select'))el.disabled=true;save('shop',pending,form.querySelector('button')).catch(()=>{});};
  }
 }
 function cancel(){epoch++;}
 function clear(){epoch++;data=null;pending=null;root.replaceChildren();}
 return{load,cancel,clear};
}
