const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>'RM'+Number(v||0).toFixed(2),number=v=>Number(v||0).toLocaleString('en-MY');
const date=v=>v?new Intl.DateTimeFormat('zh-MY',{timeZone:'Asia/Kuala_Lumpur',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'—';
const method=v=>({cash:'现金',duitnow:'DuitNow',bank_transfer:'转账',other:'其他',foodcourt:'食阁收款',card:'银行卡',qr:'扫码支付',transfer:'转账',ewallet:'电子钱包'}[v]||v||'—');
function malaysiaDay(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kuala_Lumpur',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(k=>p.find(x=>x.type===k).value).join('-');}
function shiftDay(day,n){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function csvCell(v){let s=String(v??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
export function createOwnerReports({db,root,isOwner,notice,businessDay}){
 let epoch=0,page=1,data=null,active='overview';const day=businessDay||malaysiaDay();
 root.innerHTML=`<div class="report-head"><div><p class="kicker">OWNER REPORTS</p><h2>店铺报表</h2></div><button type="button" data-report="refresh" class="quiet">刷新</button></div><nav class="tool-subtabs report-tabs" aria-label="报表类别">${[['overview','总览'],['sales','业绩'],['members','会员'],['rewards','权益']].map(([key,name])=>`<button type="button" data-report-tab="${key}" class="${key==='overview'?'active':''}">${name}</button>`).join('')}</nav><form class="report-filter" data-report="range"><label>开始<input type="date" data-report="start" value="${day.slice(0,7)}-01" required></label><label>结束<input type="date" data-report="end" value="${day}" required></label><button type="submit" class="primary">查看</button></form><div class="report-presets"><button type="button" data-report-period="today">今日</button><button type="button" data-report-period="month">本月</button><button type="button" data-report-period="30days">近30天</button><button type="button" data-report-period="year">今年</button><button type="button" data-report="export" class="quiet" disabled>导出 CSV</button></div><p data-report="status" class="field-note" role="status">正在读取…</p><section data-report-pane="overview"></section><section data-report-pane="sales" class="hidden"></section><section data-report-pane="members" class="hidden"><form class="report-member-search" data-report="searchForm"><input type="search" data-report="search" maxlength="80" placeholder="会员名字或手机号码" aria-label="查询会员"><button type="submit">查询</button></form><div data-report="memberStats"></div><div data-report="memberTable"></div><div class="report-pagination"><button type="button" data-report="prev">上一页</button><span data-report="page" role="status"></span><button type="button" data-report="next">下一页</button></div></section><section data-report-pane="rewards" class="hidden"></section>`;
 const $=key=>root.querySelector('[data-report="'+key+'"]'),pane=key=>root.querySelector('[data-report-pane="'+key+'"]');
 const card=(title,value,sub='',type='')=>`<article class="report-stat ${type}"><span>${esc(title)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</article>`;
 const grid=items=>`<div class="report-stats">${items.join('')}</div>`;
 function table(title,heads,rows){return `<details class="report-table-block" open><summary>${esc(title)} <small>${rows.length} 行</small></summary><div class="report-table-scroll"><table><thead><tr>${heads.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${heads.length}" class="report-empty">暂无记录</td></tr>`}</tbody></table></div></details>`;}
 function dailyRows(d){const byDay=new Map((d.days||[]).map(x=>[x.day,x]));const rows=[];for(let s=d.start;s<=d.end;s=shiftDay(s,1)){const x=byDay.get(s)||{};rows.push([s,number(x.orders),money(x.amount_rm)]);}return rows;}
 function setTab(tab){active=tab;for(const section of root.querySelectorAll('[data-report-pane]'))section.classList.toggle('hidden',section.dataset.reportPane!==tab);for(const b of root.querySelectorAll('[data-report-tab]'))b.classList.toggle('active',b.dataset.reportTab===tab);$('export').textContent=tab==='members'?'导出本页会员 CSV':'导出本页报表 CSV';}
 function render(d){
  const s=d.stats||{},l=d.live||{},m=d.member_stats||{},r=d.reward_activity||{};
  const alerts=[l.unbound_rewards?`${l.unbound_rewards} 种奖励未绑定可用权益`:null,l.low_stock_pool_entries?`${l.low_stock_pool_entries} 项奖池库存剩余不超过5`:null,l.expiring_rewards?`${l.expiring_rewards} 份钱包奖励将在7天内到期`:null].filter(Boolean);
  pane('overview').innerHTML=grid([card('今日实收',money(s.today_amount),number(s.today_orders)+' 张收款单','highlight'),card('本月实收',money(s.month_amount),number(s.month_orders)+' 张收款单','highlight'),card('会员总数',number(m.total),`本月新增 ${number(m.month_new)}`),card('近30日活跃会员',number(m.active_30d))])+`<div class="report-live"><h3>当前状态</h3>${grid([card('待审核',number(l.pending_orders)),card('待出品',number(l.preparing_orders)),card('待收款',number(l.unpaid_orders)),card('奖励已预留',number(l.held_rewards))])}</div>`+table('当前开放配置',['项目','数量'],[['在售商品',number(l.active_products)],['可发 Game Pass 系列',number(l.active_series)],['开放活动',number(l.active_campaigns)],['已启用奖励规则',number(l.active_rewards)],['已上架广告',number(l.active_banners)],['启用工作账号',number(l.work_accounts)]])+(alerts.length?`<div class="report-alert"><strong>需要留意</strong>${alerts.map(v=>`<p>${esc(v)}</p>`).join('')}</div>`:'');
  pane('sales').innerHTML=grid([card('所选期间实收',money(s.range_amount),number(s.range_orders)+' 张单','highlight'),card('奖励优惠',money(s.range_discount),'原价 '+money(s.range_gross)),card('售出商品',number(s.range_items)+' 份'),card('每单净实收',money(s.average_order))])+table('每日业绩',['日期','收款订单','净实收'],dailyRows(d))+table('月业绩 · 所选日期范围',['月份','收款订单','净实收'],(d.months||[]).map(x=>[x.month,number(x.orders),money(x.amount_rm)]))+table('人员收款统计',['收银账号','收款订单','净实收'],(d.cashiers||[]).map(x=>[x.username,number(x.orders),money(x.amount_rm)]))+table('收款方式',['方式','收款订单','净实收'],(d.payments||[]).map(x=>[method(x.method),number(x.orders),money(x.amount_rm)]))+table('商品销量 · 前20项',['商品','份数','原价','优惠后'],(d.products||[]).map(x=>[x.item_name,number(x.quantity),money(x.gross_rm),money(x.net_rm)]))+table('收款订单 · 最近50张',['单号','桌号','收款时间','方式','实收'],(d.orders||[]).map(x=>[x.order_no,x.table_label||'Walk-in',date(x.paid_at),method(x.payment_method),money(x.amount_rm)]));
  $('memberStats').innerHTML=grid([card('会员总数',number(m.total)),card('本月新增',number(m.month_new)),card('近30日活跃',number(m.active_30d)),card('积分余额总计',number(m.point_balance)+' P')]);
  $('memberTable').innerHTML=table('会员表 · 每页40人',['会员','手机','注册时间','最近活跃','积分','钱包奖励','Game Pass','已归属商品'],(d.members||[]).map(x=>[x.display_name,x.phone,date(x.created_at),date(x.last_activity),number(x.points),number(x.wallet_rewards),number(x.game_passes),money(x.attributed_amount)]));
  const pages=Math.max(1,Math.ceil(Number(d.member_filtered_total||0)/40));$('page').textContent=`${page} / ${pages} 页 · ${number(d.member_filtered_total)} 位`;$('prev').disabled=page<=1;$('next').disabled=page>=pages;
  pane('rewards').innerHTML=grid([card('Game Pass 待领取',number(l.unclaimed_passes)),card('已领尚未使用',number(l.claimed_passes)),card('钱包未核销奖励',number(l.wallet_rewards),'含尚未到可用日期的奖励'),card('7日内到期奖励',number(l.expiring_rewards))])+table('权益与发放状态',['项目','数量'],[['在售积分兑换项目',number(l.active_point_shop_items)],['开放奖励领取码',number(l.active_offers)],['近24小时未完成游戏',number(l.open_game_sessions)],['订单已预留奖券',number(l.held_rewards)],['未绑定可用权益的奖励种类',number(l.unbound_rewards)],['积分余额总计',number(m.point_balance)]])+table('奖励种类 · 前100项',['奖励','期间发放','期间核销','当前未核销','7日内到期'],(d.reward_types||[]).map(x=>[x.reward_name,number(x.issued),number(x.redeemed),number(x.outstanding),number(x.expiring)]))+table('所选期间权益流水',['项目','数量'],[['积分商场兑换',number(r.point_exchanges)],['奖励发放',number(r.issued)],['奖励核销',number(r.redeemed)],['Game Pass 领取',number(r.passes_claimed)],['完成游戏',number(r.games_completed)],['发出积分',number(r.points_earned)+' P'],['花费积分',number(r.points_spent)+' P']]);
  $('status').textContent=`${d.start} — ${d.end} · 更新 ${date(d.generated_at)} · 马来西亚时间`;$('export').disabled=false;setTab(active);
 }
 async function load(){
  if(!isOwner()){notice('仅限 Owner 查看报表',true);return;}const current=++epoch;$('export').disabled=true;$('status').textContent='正在读取报表…';
  const start=$('start').value,end=$('end').value;if(!start||!end||start>end||(new Date(end)-new Date(start))/86400000>365){$('status').textContent='请选择最多366天的有效日期范围。';return;}
  try{const response=await db.rpc('yt_owner_report_v8',{p_start:start,p_end:end,p_member_page:page,p_search:$('search').value.trim()});if(current!==epoch)return;if(response.error)throw Error(response.error.message);if(!response.data)throw Error('报表暂不可用');data=response.data;render(data);}catch(e){if(current!==epoch)return;$('status').textContent='加载失败，点击刷新重试。';notice(e.message==='owner_only'?'仅限 Owner 查看报表':e.message,true);}
 }
 function exportRows(){if(!data||!isOwner())return;
  let rows;if(active==='members')rows=[['会员','手机','注册时间','最近活跃','积分','钱包奖励','Game Pass','已归属商品RM'],...(data.members||[]).map(x=>[x.display_name,x.phone,date(x.created_at),date(x.last_activity),x.points,x.wallet_rewards,x.game_passes,Number(x.attributed_amount||0).toFixed(2)])];
  else if(active==='sales')rows=[['每日业绩'],['日期','收款订单','净实收'],...dailyRows(data),[],['月业绩·所选日期范围'],['月份','收款订单','净实收'],...(data.months||[]).map(x=>[x.month,x.orders,money(x.amount_rm)]),[],['人员收款统计'],['账号','收款订单','净实收'],...(data.cashiers||[]).map(x=>[x.username,x.orders,money(x.amount_rm)]),[],['收款方式','收款订单','净实收'],...(data.payments||[]).map(x=>[method(x.method),x.orders,money(x.amount_rm)]),[],['商品销量·前20项'],['商品','份数','原价','优惠后'],...(data.products||[]).map(x=>[x.item_name,x.quantity,money(x.gross_rm),money(x.net_rm)]),[],['收款订单·最近50张'],['单号','桌号','时间','方式','实收'],...(data.orders||[]).map(x=>[x.order_no,x.table_label,date(x.paid_at),method(x.payment_method),money(x.amount_rm)])];
  else rows=[['报表类别',active==='overview'?'总览':'权益'],['范围',data.start,data.end],...[...pane(active).querySelectorAll('.report-stat')].map(x=>[x.querySelector('span').textContent,x.querySelector('strong').textContent]),...[...pane(active).querySelectorAll('table tr')].map(x=>[...x.querySelectorAll('th,td')].map(v=>v.textContent))];
  const csv='\uFEFF'+rows.map(row=>row.map(csvCell).join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`Yetipsy-${active}-${data.start}-${data.end}${active==='members'?'-page'+page:''}.csv`;root.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
 }
 $('range').onsubmit=e=>{e.preventDefault();page=1;load();};$('searchForm').onsubmit=e=>{e.preventDefault();page=1;load();};$('refresh').onclick=()=>load();$('prev').onclick=()=>{if(page>1){page--;load();}};$('next').onclick=()=>{if(data&&page*40<data.member_filtered_total){page++;load();}};$('export').onclick=exportRows;
 for(const b of root.querySelectorAll('[data-report-tab]'))b.onclick=()=>setTab(b.dataset.reportTab);
 for(const b of root.querySelectorAll('[data-report-period]'))b.onclick=()=>{const today=data?.business_day||businessDay||malaysiaDay(),key=b.dataset.reportPeriod;$('end').value=today;$('start').value=key==='today'?today:key==='month'?today.slice(0,7)+'-01':key==='year'?today.slice(0,4)+'-01-01':shiftDay(today,-29);page=1;load();};
 return {load,cancel(){epoch++;},clear(){epoch++;data=null;for(const key of ['overview','sales','rewards'])pane(key).replaceChildren();$('memberStats').replaceChildren();$('memberTable').replaceChildren();$('export').disabled=true;$('status').textContent='请登录 Owner 后重新读取。';}};
}
