const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const stamp=value=>value?new Intl.DateTimeFormat('zh-MY',{timeZone:'Asia/Kuala_Lumpur',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';
const rpc=async(db,name,args)=>{const result=await db.rpc(name,args);if(result.error)throw Error(result.error.message||result.error.code||'server_unavailable');return result.data};
let qrWait=null;
async function qrReady(){
 if(window.QRCode?.CorrectLevel)return true;
 if(!qrWait)qrWait=(async()=>{for(const src of ['https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js','https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js']){try{await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src=src;script.onload=resolve;script.onerror=reject;document.head.append(script)});if(window.QRCode?.CorrectLevel)return true;}catch{}}return false;})();
 return qrWait;
}

export function createStoreBox({db,ownerRoot,staffRoot,isOwner,notice}){
 const state={rules:[],staffTab:'queue',orders:[],selectedOrder:'',quote:null,claims:[],queue:[],boxes:[],qr:null,epoch:0,timer:null};
 const say=(message,bad=false)=>notice?.(message,bad);
 const modeLabel=mode=>mode==='challenge'?'挑战':'套餐';
 const statusLabel=status=>({unclaimed:'待领取',active:'使用中',paused:'已暂停',exhausted:'已全部出杯',completed:'已完成',expired:'已到期',cancelled:'已取消',pending:'待处理',accepted:'已接单',preparing:'准备中',served:'已出杯'}[status]||status);
 const busy=async(button,work)=>{if(button?.disabled)return;if(button)button.disabled=true;try{return await work();}catch(error){say(error.message||'操作失败',true);throw error;}finally{if(button)button.disabled=false;}};

 function ownerMarkup(){return `<article class="card storebox-owner"><div class="block-head"><div><p class="kicker">STORE BOX</p><h2>存酒规则</h2></div><button type="button" class="quiet" data-box-owner-refresh>刷新</button></div>
  <form class="stack" data-box-rule-form><label>商品<select data-box-product required></select></label><div class="pair"><label>类型<select data-box-mode><option value="package">套餐</option><option value="challenge">挑战</option></select></label><label>单位<input data-box-unit maxlength="12" value="杯" required></label></div>
  <div class="storebox-rule-grid"><label>每套数量<input data-box-total type="number" min="1" max="999" value="6" required></label><label>单次上限<input data-box-limit type="number" min="1" max="99" value="2" required></label><label>保存天数<input data-box-days type="number" min="1" max="3650" value="30" required></label></div>
  <label class="checkline"><input data-box-active type="checkbox" checked><span>启用此商品的存酒箱</span></label><button type="submit" class="main-button">保存规则</button></form></article><section data-box-rule-list class="storebox-rule-list"></section>`;}
 function fillOwnerForm(productId){const row=state.rules.find(item=>item.product_id===productId),form=ownerRoot.querySelector('[data-box-rule-form]');if(!form)return;
  form.querySelector('[data-box-mode]').value=row?.mode||'package';form.querySelector('[data-box-total]').value=row?.total_units||6;form.querySelector('[data-box-limit]').value=row?.request_limit||2;form.querySelector('[data-box-days]').value=row?.expiry_days||30;form.querySelector('[data-box-unit]').value=row?.unit_label||'杯';form.querySelector('[data-box-active]').checked=row?.active!==false;}
 function renderOwner(){if(!ownerRoot)return;if(!ownerRoot.querySelector('[data-box-rule-form]'))ownerRoot.innerHTML=ownerMarkup();
  const select=ownerRoot.querySelector('[data-box-product]'),current=select.value;select.replaceChildren(new Option('选择菜单商品',''));state.rules.forEach(row=>select.add(new Option(`${row.title}${row.mode?' · '+modeLabel(row.mode):''}`,row.product_id)));if(state.rules.some(row=>row.product_id===current))select.value=current;
  const configured=state.rules.filter(row=>row.mode);ownerRoot.querySelector('[data-box-rule-list]').innerHTML=configured.length?configured.map(row=>`<button type="button" class="storebox-rule-card" data-box-edit-rule="${esc(row.product_id)}"><span><strong>${esc(row.title)}</strong><small>${modeLabel(row.mode)} · ${row.total_units}${esc(row.unit_label)} · 每次最多 ${row.request_limit}${esc(row.unit_label)}</small></span><em>${row.active?'启用':'暂停'}</em></button>`).join(''):'<div class="card empty">还没有设置存酒商品。</div>';
 }
 async function loadOwner(){if(!isOwner())throw Error('owner_only');if(!ownerRoot)return;ownerRoot.innerHTML='<div class="card"><div class="empty">正在读取存酒规则…</div></div>';state.rules=await rpc(db,'yt_store_box_rule_list');renderOwner();}
 async function saveOwnerRule(button){const form=ownerRoot.querySelector('[data-box-rule-form]'),product=form.querySelector('[data-box-product]').value;if(!product)throw Error('请选择商品');await busy(button,async()=>{await rpc(db,'yt_store_box_rule_save',{p_product:product,p_mode:form.querySelector('[data-box-mode]').value,p_total_units:Number(form.querySelector('[data-box-total]').value),p_request_limit:Number(form.querySelector('[data-box-limit]').value),p_expiry_days:Number(form.querySelector('[data-box-days]').value),p_unit_label:form.querySelector('[data-box-unit]').value.trim(),p_completion_reward:null,p_game_pass_enabled:false,p_active:form.querySelector('[data-box-active]').checked});say('存酒规则已保存');await loadOwner();ownerRoot.querySelector('[data-box-product]').value=product;fillOwnerForm(product);});}

 function staffShell(){return `<div class="storebox-head"><div><p class="kicker">STORE BOX</p><h2>存酒箱</h2></div><button type="button" class="quiet" data-box-refresh>刷新</button></div><nav class="subtabs storebox-tabs"><button type="button" data-box-tab="queue">叫酒</button><button type="button" data-box-tab="issue">发领取码</button></nav><section data-box-staff-body></section>`;}
 function queueMarkup(){const requests=state.queue.length?state.queue.map(row=>`<article class="storebox-request"><div class="storebox-row-head"><div><strong>${esc(row.name)} · ${row.quantity}${esc(row.unit_label)}</strong><small>${esc(row.table_label||row.customer_name||'未填桌号')} · ${stamp(row.requested_at)}</small></div><span>${statusLabel(row.status)}</span></div><div class="storebox-progress"><b>剩 ${row.remaining_units}</b><small>已出 ${row.served_units} · 喝完 ${row.completed_units} / ${row.total_units}</small></div><div class="action-row">${row.status==='pending'?`<button type="button" class="primary" data-box-request-action="accept" data-request="${esc(row.request_id)}">接单</button>`:''}<button type="button" class="main-button" data-box-request-action="serve" data-request="${esc(row.request_id)}">确认出杯</button><button type="button" class="quiet" data-box-request-action="cancel" data-request="${esc(row.request_id)}">取消</button></div></article>`).join(''):'<div class="empty">目前没有叫酒请求。</div>';
  const boxes=state.boxes.length?state.boxes.map(row=>`<article class="storebox-box"><div class="storebox-row-head"><div><strong>${esc(row.name)}</strong><small>${esc(row.customer_name||'会员')} · ${esc(row.table_label||'未填桌号')}</small></div><span>${statusLabel(row.status)}</span></div><div class="storebox-meter"><i style="width:${Math.min(100,Number(row.served_units)*100/Math.max(1,Number(row.total_units)))}%"></i></div><div class="storebox-counts"><span>剩余 <b>${row.remaining_units}</b></span><span>已出 <b>${row.served_units}</b></span><span>喝完 <b>${row.completed_units}</b></span></div><div class="action-row">${Number(row.completed_units)<Number(row.served_units)?`<button type="button" data-box-progress="complete" data-box="${esc(row.id)}">喝完 +1</button>`:''}<button type="button" class="quiet" data-box-progress="${row.status==='paused'?'resume':'pause'}" data-box="${esc(row.id)}">${row.status==='paused'?'恢复':'暂停'}</button></div></article>`).join(''):'<div class="empty">还没有已领取的存酒箱。</div>';
  return `<section class="card"><div class="block-head"><h3>叫酒请求</h3><span class="mini-chip">${state.queue.length}</span></div><div class="storebox-stack">${requests}</div></section><section class="card"><div class="block-head"><h3>进行中</h3><span class="mini-chip">${state.boxes.length}</span></div><div class="storebox-stack">${boxes}</div></section>`;}
 function issueItem(row){const claimed=row.box_id&&row.customer_id;const active=row.active_claim_id&&row.claim_token;
  return `<article class="storebox-issue-item"><div><strong>${esc(row.item_name)}</strong><small>${modeLabel(row.mode)} · ${row.total_units}${esc(row.unit_label)} · 每次最多 ${row.request_limit}${esc(row.unit_label)}</small></div><div class="action-row">${active?`<button type="button" class="primary" data-box-show-claim="${esc(row.active_claim_id)}">显示 QR</button><button type="button" class="quiet" data-box-cancel-claim="${esc(row.active_claim_id)}">取消</button>`:claimed?'<span class="mini-chip">已领取</span>':`<button type="button" class="main-button" data-box-issue="${esc(row.order_item_id)}">生成 QR</button>`}</div></article>`;}
 function issueMarkup(){const options=state.orders.map(row=>`<option value="${esc(row.id)}"${row.id===state.selectedOrder?' selected':''}>#${esc(row.order_no||'—')} · ${esc(row.table_label||'Walk-in')}</option>`).join('');const items=state.quote?.items?.length?state.quote.items.map(issueItem).join(''):'<div class="empty">选择当天已付款的套餐订单。</div>';
  const active=state.claims.length?state.claims.map(row=>`<article class="storebox-claim"><div><strong>#${esc(row.order_no||'—')} · ${esc(row.name)}</strong><small>${esc(row.table_label||'Walk-in')} · ${esc(row.issued_by_name||'Staff')} · ${stamp(row.expires_at)}</small></div><div class="action-row"><button type="button" data-box-show-claim="${esc(row.claim_id)}">显示 QR</button><button type="button" class="quiet" data-box-cancel-claim="${esc(row.claim_id)}">取消</button></div></article>`).join(''):'<div class="empty">没有等待领取的二维码。</div>';
  return `<section class="card"><label>当天已付款订单<select data-box-order><option value="">请选择订单</option>${options}</select></label><div class="storebox-stack">${items}</div><div data-box-qr></div></section><section class="card"><div class="block-head"><h3>全店待领取码</h3><span class="mini-chip">${state.claims.length}</span></div><div class="storebox-stack">${active}</div></section>`;}
 function renderStaff(){if(!staffRoot)return;if(!staffRoot.querySelector('[data-box-staff-body]'))staffRoot.innerHTML=staffShell();for(const button of staffRoot.querySelectorAll('[data-box-tab]'))button.classList.toggle('active',button.dataset.boxTab===state.staffTab);staffRoot.querySelector('[data-box-staff-body]').innerHTML=state.staffTab==='issue'?issueMarkup():queueMarkup();if(state.qr&&state.staffTab==='issue')showQR(state.qr);}
 async function loadQuote(){state.quote=state.selectedOrder?await rpc(db,'yt_store_box_issue_quote',{p_order:state.selectedOrder}):null;}
 async function loadStaff(silent=false){if(!staffRoot)return;const epoch=++state.epoch;if(!silent)staffRoot.innerHTML='<div class="card"><div class="empty">正在读取存酒箱…</div></div>';try{const [orders,claims,queue,boxes]=await Promise.all([rpc(db,'yt_store_box_issue_orders'),rpc(db,'yt_store_box_claims_active'),rpc(db,'yt_store_box_queue'),rpc(db,'yt_store_box_staff_boxes')]);if(epoch!==state.epoch)return;state.orders=orders.orders||[];state.claims=claims||[];state.queue=queue||[];state.boxes=boxes||[];if(!state.orders.some(row=>row.id===state.selectedOrder))state.selectedOrder='';await loadQuote();if(epoch!==state.epoch)return;renderStaff();}catch(error){if(!silent)staffRoot.innerHTML=`<div class="card"><div class="empty">${esc(error.message||'读取失败')}</div></div>`;throw error;}}
 async function showQR(row){state.qr=row;const root=staffRoot.querySelector('[data-box-qr]');if(!root)return;clearInterval(state.timer);root.className='storebox-qr-card';root.replaceChildren();const title=document.createElement('h3');title.textContent=row.name||'存酒箱领取';const square=document.createElement('div');square.className='qr-screen';const help=document.createElement('p');help.className='help';root.append(title,square,help);const url=new URL('../',import.meta.url);url.searchParams.set('box',row.claim_token);if(await qrReady())new window.QRCode(square,{text:url.href,width:206,height:206,colorDark:'#1d251f',colorLight:'#fff',correctLevel:window.QRCode.CorrectLevel.M});else square.textContent='二维码暂时无法加载，请刷新重试。';const tick=()=>{const seconds=Math.max(0,Math.ceil((Date.parse(row.expires_at)-Date.now())/1000));help.textContent=seconds?`请顾客在 ${seconds} 秒内领取`:'二维码已过期';if(!seconds){square.classList.add('code-expired');clearInterval(state.timer);}};tick();state.timer=setInterval(tick,1000);root.scrollIntoView({behavior:'smooth',block:'center'});}
 async function issue(item,button){await busy(button,async()=>{const result=await rpc(db,'yt_store_box_issue',{p_order_item:item,p_token:crypto.randomUUID(),p_request:crypto.randomUUID(),p_minutes:2});state.qr=result;await loadStaff(true);say('存酒箱领取码已生成，全体员工都能重新显示');});}
 async function cancelClaim(id,button){const reason=window.prompt('取消原因','重新发码');if(reason===null)return;await busy(button,async()=>{await rpc(db,'yt_store_box_claim_cancel',{p_claim:id,p_reason:reason.trim()});if(state.qr?.claim_id===id)state.qr=null;await loadStaff(true);say('领取码已取消，可以重新生成');});}
 async function requestAction(id,action,button){let completed=0,reason='';if(action==='serve'){const row=state.queue.find(item=>item.request_id===id);const answer=window.prompt('同时确认已喝完几杯？没有就填 0','0');if(answer===null)return;completed=Number(answer);if(!Number.isInteger(completed)||completed<0||completed>Number(row?.served_units||0)+Number(row?.quantity||0)-Number(row?.completed_units||0))throw Error('喝完杯数不正确');}if(action==='cancel'){reason=window.prompt('取消原因','现场调整');if(reason===null)return;}await busy(button,async()=>{await rpc(db,'yt_store_box_request_action',{p_request:id,p_action:action,p_completed_delta:completed,p_reason:reason.trim()});await loadStaff(true);say(action==='serve'?'已记录出杯':action==='accept'?'已接单':'请求已取消');});}
 async function progress(box,action,button){await busy(button,async()=>{await rpc(db,'yt_store_box_progress',{p_box:box,p_action:action,p_completed_delta:action==='complete'?1:0});await loadStaff(true);say(action==='complete'?'已增加一杯完成记录':action==='pause'?'存酒箱已暂停':'存酒箱已恢复');});}

 if(ownerRoot){ownerRoot.addEventListener('submit',event=>{if(!event.target.matches('[data-box-rule-form]'))return;event.preventDefault();saveOwnerRule(event.submitter).catch(()=>{});});ownerRoot.addEventListener('change',event=>{if(event.target.matches('[data-box-product]'))fillOwnerForm(event.target.value);});ownerRoot.addEventListener('click',event=>{const edit=event.target.closest('[data-box-edit-rule]');if(edit){ownerRoot.querySelector('[data-box-product]').value=edit.dataset.boxEditRule;fillOwnerForm(edit.dataset.boxEditRule);ownerRoot.querySelector('[data-box-rule-form]').scrollIntoView({behavior:'smooth'});}if(event.target.closest('[data-box-owner-refresh]'))loadOwner().catch(error=>say(error.message,true));});}
 if(staffRoot){staffRoot.addEventListener('change',event=>{if(event.target.matches('[data-box-order]')){state.selectedOrder=event.target.value;state.qr=null;loadQuote().then(renderStaff).catch(error=>say(error.message,true));}});staffRoot.addEventListener('click',event=>{const tab=event.target.closest('[data-box-tab]');if(tab){state.staffTab=tab.dataset.boxTab;state.qr=null;renderStaff();return;}if(event.target.closest('[data-box-refresh]')){loadStaff().catch(error=>say(error.message,true));return;}const issueButton=event.target.closest('[data-box-issue]');if(issueButton)issue(issueButton.dataset.boxIssue,issueButton).catch(()=>{});const show=event.target.closest('[data-box-show-claim]');if(show){const row=state.claims.find(item=>item.claim_id===show.dataset.boxShowClaim)||state.quote?.items?.find(item=>item.active_claim_id===show.dataset.boxShowClaim);if(row)showQR({claim_id:row.claim_id||row.active_claim_id,claim_token:row.claim_token,expires_at:row.expires_at||row.claim_expires_at,name:row.name||row.item_name});}const cancel=event.target.closest('[data-box-cancel-claim]');if(cancel)cancelClaim(cancel.dataset.boxCancelClaim,cancel).catch(()=>{});const action=event.target.closest('[data-box-request-action]');if(action)requestAction(action.dataset.request,action.dataset.boxRequestAction,action).catch(error=>say(error.message,true));const change=event.target.closest('[data-box-progress]');if(change)progress(change.dataset.box,change.dataset.boxProgress,change).catch(()=>{});});}
 function clear(){state.epoch++;clearInterval(state.timer);state.rules=[];state.orders=[];state.claims=[];state.queue=[];state.boxes=[];state.quote=null;state.qr=null;if(ownerRoot)ownerRoot.innerHTML='<div class="card"><div class="empty">请使用 Owner 登录。</div></div>';if(staffRoot)staffRoot.innerHTML='<div class="card"><div class="empty">请先登录工作台。</div></div>';}
 function cancel(){state.epoch++;clearInterval(state.timer);state.qr=null;}
 return {loadOwner,loadStaff,clear,cancel};
}
