const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');const {webcrypto}=require('node:crypto');
const source=fs.readFileSync(path.join(__dirname,'../play/owner-banners.js'),'utf8').replace(/export /g,'');
class El{constructor(){this.value='';this.checked=true;this.files=[];this.disabled=false;this.dataset={};this.textContent='';this.hidden=false;this.classList={add(){},remove(){},toggle(){}};}focus(){}setAttribute(k,v){this[k]=v;}getClientRects(){return [1];}}
const nodes=Object.fromEntries(['title','image','sort','enabled','form','preview','save','new','status','list'].map(k=>[k,new El()]));nodes.sort.value='10';nodes.form.reset=()=>{nodes.title.value='';nodes.image.files=[];nodes.sort.value='10';nodes.enabled.checked=true;};
const root={innerHTML:'',querySelector(s){const name=s.match(/name="([^"]+)"/);if(name)return nodes[name[1]];return nodes[({'form':'form','.banner-upload-preview':'preview','button[type="submit"]':'save','[data-banner-new]':'new','.banner-save-status':'status','.banner-manager-list':'list'})[s]];},querySelectorAll(){return Object.values(nodes);}};
const uploads=[],saves=[],notices=[];let rows=[],reject=true,published=0,bitmapClosed=0,canvas;
const db={storage:{from:()=>({getPublicUrl:p=>({data:{publicUrl:'https://test.supabase.co/storage/v1/object/public/banners/'+p}}),upload:async(p,blob,options)=>{uploads.push({p,blob,options});return {data:{path:p}};}})},rpc:async(n,a)=>{if(n==='yt_owner_banner_list')return {data:rows};saves.push(a);if(reject)return {error:{message:'retry save'}};rows=[{id:'banner',title:a.p_title,image_path:a.p_image_path,sort_order:a.p_sort,enabled:a.p_enabled}];return {data:'banner'};}};
const c={console,Blob,crypto:webcrypto,URL:{createObjectURL:()=> 'blob:preview',revokeObjectURL(){}},createImageBitmap:async()=>({width:3200,height:1800,close:()=>bitmapClosed++}),document:{createElement(){canvas={getContext:()=>({fillRect(){},drawImage(){}}),toBlob:cb=>cb(new Blob(['jpeg'],{type:'image/jpeg'}))};return canvas;}}};
vm.createContext(c);vm.runInContext(source+'\nglobalThis.test={validateBannerFile,createBannerManager};',c);
(async()=>{
 assert.throws(()=>c.test.validateBannerFile({type:'image/svg+xml',size:1}),/请选择/);assert.throws(()=>c.test.validateBannerFile({type:'image/jpeg',size:6*1024*1024}),/5 MB/);
 const manager=c.test.createBannerManager({db,root,notify:(m,b)=>notices.push({m,b}),onPublished:async()=>published++});await manager.load();nodes.title.value='本周新品';nodes.image.files=[{type:'image/png',size:1000}];nodes.sort.value='2';
 await nodes.form.onsubmit({preventDefault(){}});assert.equal(uploads.length,1);assert.equal(saves.length,1);assert.match(nodes.status.textContent,/retry save/);assert(Object.values(nodes).every(x=>!x.disabled));assert.equal(canvas.width,1600);assert.equal(canvas.height,900);assert.equal(bitmapClosed,1);assert.equal(uploads[0].options.upsert,false);
 reject=false;await nodes.form.onsubmit({preventDefault(){}});assert.equal(uploads.length,1,'saved upload path reused on metadata retry');assert.equal(saves[0].p_image_path,saves[1].p_image_path);assert.equal(published,1);assert.match(nodes.status.textContent,/首页已更新/);
 nodes.list.onclick({target:{closest:()=>({dataset:{bannerEdit:'banner'}})}});assert.equal(nodes.title.value,'本周新品');nodes.enabled.checked=false;await nodes.form.onsubmit({preventDefault(){}});assert.equal(saves.at(-1).p_enabled,false);assert.equal(saves.at(-1).p_id,'banner');assert.equal(uploads.length,1);
 const carouselSource=fs.readFileSync(path.join(__dirname,'../play/home-carousel.js'),'utf8').replace(/^import .*?;\n/,'').replace(/export /g,'');
 const adRoot=new El();adRoot.querySelector=()=>new El();let adSlides=[],dots=[];Object.defineProperty(adRoot,'innerHTML',{set(v){this.markup=v;adSlides=[...v.matchAll(/class="home-ad-slide /g)].map(()=>new El());dots=adSlides.map(()=>new El());},get(){return this.markup;}});adRoot.querySelectorAll=s=>s==='.home-ad-slide'?adSlides:dots;
 let tick,response=[];const cc={BANNER_BUCKET:'banners',document:{visibilityState:'visible'},window:{matchMedia:()=>({matches:false})},setInterval:f=>{tick=f;return 1;},clearInterval(){}};vm.createContext(cc);vm.runInContext(carouselSource+'\nglobalThis.create=createHomeCarousel;',cc);
 const adDB={storage:db.storage,rpc:async()=>({data:response})};const carousel=cc.create({db:adDB,root:adRoot});assert.equal(adSlides.length,2);response=[{title:'<promo>',image_path:'ads/x.jpg'},{title:'第二张',image_path:'ads/y.jpg'}];await carousel.refresh();assert(adRoot.markup.includes('&lt;promo&gt;'));tick();assert.equal(adSlides[0].hidden,true);assert.equal(adSlides[1].hidden,false);cc.document.visibilityState='hidden';tick();assert.equal(adSlides[1].hidden,false);
 response=[];await carousel.refresh();assert(adRoot.markup.includes('YOUR REWARDS CLUB'));
 console.log('PASS: image validation/compression, immutable uploads, safe save retry, Owner edits/unpublish, escaped carousel titles, rotation and hidden-page pause.');
})().catch(e=>{console.error(e);process.exitCode=1;});
