const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync('play/app.js','utf8'),pos=fs.readFileSync('play/pos/pos.js','utf8');
function section(start,end){return src.slice(src.indexOf(start),src.indexOf(end,src.indexOf(start)));}
class El{constructor(){this.children=[];this.value='';this.innerHTML='';this.classList={toggle(){},add(){},remove(){}};}append(e){this.children.push(e);}querySelector(){return this.grid??=new El();}remove(){this.removed=true;}}
const els=new Map(),$=id=>{if(!els.has(id))els.set(id,new El());return els.get(id);};
let calls=[],sheets=[],closed=0,nav=[],resumed;
const ctx={URL,Date,document:{createElement:()=>new El()},$,state:{user:{id:'member'},games:[{id:'game',slug:'moon-dice',title:'dice'}],passes:[]},symbols:{},titles:{},gameTips:{},esc:String,fmt:String,millis:Date.parse,showSheet:(...a)=>sheets.push(a),sheetHtml:s=>sheets.push(s),closeSheet:()=>closed++,navigate:n=>nav.push(n),toast(){},loadGames:async()=>{},pending:async(b,f)=>f(),pinRequest:async()=>({preview:{valid:true,game_count:1,expires_at:'2030-01-01'}}),isStaff:()=>false,unpack:r=>r.data,db:{rpc:async(name,args)=>{calls.push({name,args});return {data:[]};},from:()=>({select:()=>({eq:async()=>({data:[{game_id:'game'}]})})})},redeemScanValue:async(...args)=>calls.push({name:'claimed',args}),updateHome(){},actionOnce:async()=>assert.fail('completed rounds must not start new attempts'),arena:()=>({querySelector:id=>id==='#ytBarScores'?{children:[new El(),new El(),new El()]}:new El()}),gameCheckpoint:async()=>assert.fail('completed rounds must not checkpoint again')};
vm.createContext(ctx);vm.runInContext(section('function tokenDetails(','const requestStore=')+section('async function previewClaim(','async function redeemScanValue(')+section('async function chooseGame(','function showGameIntro(')+section('async function playStopBar(','const rankSlugs=')+section('async function existingGamePass(','async function gameCheckpoint('),ctx);
(async()=>{
 const token='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';await ctx.previewClaim('claim:'+token);assert.equal(calls.length,0);assert(sheets.at(-1).includes('确认领取后3天内有效'));await $('previewAction').children[0].onclick();assert.equal(calls.at(-1).name,'claimed');
 calls=[];await ctx.chooseGame({campaign_id:'campaign',expires_at:'2030-01-01'});const root=$('sheetBody').children.at(-1),later=root.children.at(-1);assert(later.textContent.includes('稍后再玩'));later.onclick();assert.equal(closed,1);assert.deepEqual(nav,['home']);assert.equal(calls.length,0);
 const result=await ctx.playStopBar({session_id:'same'},{rounds:[100,0,70]});assert.equal(result.score,100);assert.equal(result.headline,'100%');assert(result.visual.includes('100%'));
 ctx.refreshPasses=async()=>{ctx.state.passes=[{id:'pass',session_id:'original',result_key:'R4',game_id:'original-game',game_slug:'mystery-card',game_title:'Cards'}];};ctx.startGame=async(...args)=>{resumed=args;};await ctx.resumeGamePass({id:'pass'});assert.equal(resumed[1].id,'original-game');assert.equal(resumed[2].session_id,'original');assert.equal(resumed[2].result_key,'R4');assert.equal(resumed[2].status,'resumed');
 const pcalls=[],pctx={state:{benefitTimer:null,shownBenefit:{}},$,prompt:()=> '重新分配',unpack:r=>r.data,busy:async(b,f)=>f(),clearInterval(){},showNotice(){},loadBenefits:async()=>{},sessionStorage:{removeItem(){}},bundleKey:id=>id,db:{rpc:async(name,args)=>{pcalls.push({name,args});return {data:{}};}}};vm.createContext(pctx);vm.runInContext(pos.slice(pos.indexOf('async function cancelBenefitCode('),pos.indexOf('\n',pos.indexOf('async function cancelBenefitCode('))),pctx);$('benefitOrderSelect').value='order';await pctx.cancelBenefitCode({pass:'pass',expiry:'2030-01-01'},new El());assert.equal(pcalls[0].name,'yt_pos_cancel_code');assert.equal(pcalls[0].args.p_expected_expiry,'2030-01-01');assert.equal(pcalls[0].args.p_bundle,null);assert.equal(pctx.state.shownBenefit,null);
 assert(pos.includes("db.rpc('yt_pos_benefit_orders')"));assert(pos.includes('available.find(x=>x.is_default).id'));assert(pos.includes("u.pass_status==='issued'"));
 console.log('PASS: explicit claim confirmation, defer without starting, completed skill rounds display 100% without new attempts, same-session resume, cancellation expiry snapshot, current-day options and default campaign.');
})().catch(e=>{console.error(e);process.exitCode=1;});
