const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
const src=fs.readFileSync('play/app.js','utf8');
class El{constructor(){this.children=[];this.disabled=false;this.textContent='';this.innerHTML='';this.dataset={};this.classList={add(){},remove(){}};}append(b){this.children.push(b);}after(b){this.sibling=b;}remove(){this.removed=true;}replaceChildren(){this.children=[];}querySelector(){return this.seal??=new El();}}
const els=new Map(),$=id=>{if(!els.has(id))els.set(id,new El());return els.get(id);};const root=new El(),storage=new Map();let calls=[],fail=false,success=0,nav=[];
const c={state:{user:{id:'member'}},document:{querySelector:()=>root,createElement:()=>new El()},$,esc:String,fmt:String,uuid:()=>webcrypto.randomUUID(),requestStore:{get:k=>storage.get(k),set:(k,v)=>storage.set(k,v),remove:k=>storage.delete(k)},showSheet(){},sheetHtml(){},pending:async(b,f)=>f(),toast(){},console,confirm:()=>true,closeSheet(){},navigate:x=>nav.push(x),updateGameRecordMessage(){},wallet:async()=>{},refreshPasses:async()=>{},loadMyLoyalty:async()=>{},showSimpleSuccess:async()=>success++,unpack:r=>{if(r.error)throw r.error;return r.data;},db:{rpc:async(name,args)=>{calls.push({name,args:structuredClone(args)});if(fail)throw Error('lost response');if(name==='yt_game_settle')return{data:{choice:args.p_choice,points:100}};if(name==='yt_point_shop_exchange')return{data:{reward_name:'RM5'}};return{data:{balance:500,items:[{id:'item',name:'RM5',points_cost:50,validity_days:30}]}};}}};vm.createContext(c);vm.runInContext(src.slice(src.indexOf('async function showGameSettlement('),src.indexOf('async function loadMyLoyalty(')),c);
(async()=>{
 const session={session_id:'same'},game={slug:'moon-dice'};await c.showGameSettlement(session,game,{mode:'chance',reward_name:'RM5',points:75});assert.equal(calls.length,0);const first=$('ytOpenResultReward'),other=first.sibling;fail=true;await first.onclick();assert(other.disabled);const frozen=calls.at(-1).args;await other.onclick();assert.equal(calls.length,1);fail=false;await first.onclick();assert.deepEqual(calls.at(-1).args,frozen);assert(!first.removed);assert(other.removed);first.onclick();assert.deepEqual(nav,['wallet']);
 els.clear();calls=[];await c.showGameSettlement(session,{slug:'stop-the-bar'},{mode:'skill',points:100,points_max:100});assert.equal(calls.length,1);assert.equal(calls[0].args.p_choice,'points');assert.equal($('ytOpenResultReward').textContent,'查看我的积分与商场 ↗');assert(!$('ytOpenResultReward').removed);
 calls=[];fail=true;const item={id:'item',name:'RM5',points_cost:50};await assert.rejects(c.exchangeShopItem(item,'member'),/lost response/);const saved=JSON.parse(storage.get('points-shop:member'));assert(saved.request);const original=calls.at(-1).args;
 // Simulate a page reload: session storage recovers the same item, request and confirmed price.
 vm.runInContext('pointsShopPending=null;',c);fail=false;await c.openPointsShop();await c.exchangeShopItem({...item,points_cost:99},'member');const exchange=calls.filter(x=>x.name==='yt_point_shop_exchange');assert.deepEqual(exchange[1].args,original);assert.equal(exchange[1].args.p_expected_cost,50);assert.equal(success,1);assert(!storage.has('points-shop:member'));
 assert(!src.includes("db.rpc('yt_claim_random_points'"));assert(!src.includes('不玩游戏 · 随机领积分'));assert(src.includes("localResult.headline=record.achievement_percent+'%'"));
 for(const role of ['pos','owner','staff','cashier']){const html=fs.readFileSync(`play/${role}/index.html`,'utf8');assert(html.includes('id="ownerPointsRoot"'));assert(html.includes('20261010-storebox-v16-1'));}
 console.log('PASS: explicit chance choice, immutable lost-response retry, skill auto-points, visible completion button, drawer exchange recovery across reload with original price, no random-point shortcut and all Owner aliases.');
})().catch(e=>{console.error(e);process.exitCode=1;});
