const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
class El{constructor(){this.value='';this.disabled=false;this.children=[];this.dataset={};this.textContent='';this.innerHTML='';this.flags=new Set();this.classList={toggle:(k,v)=>v?this.flags.add(k):this.flags.delete(k)};}querySelectorAll(){return [];}replaceChildren(){this.innerHTML='';this.children=[];}append(el){this.children.push(el);}click(){if(this.onclick)this.onclick();}remove(){}}
const keys=['refresh','range','start','end','export','status','search','searchForm','memberStats','memberTable','prev','page','next'],els=Object.fromEntries(keys.map(k=>[k,new El()])),panes=Object.fromEntries(['overview','sales','members','rewards'].map(k=>{const x=new El();x.dataset.reportPane=k;return [k,x];})),tabs=Object.keys(panes).map(k=>{const x=new El();x.dataset.reportTab=k;return x;}),periods=['today','month','30days','year'].map(k=>{const x=new El();x.dataset.reportPeriod=k;return x;});
const root=new El();root.querySelector=s=>{const m=s.match(/\[data-report="(.*?)"\]/);if(m)return els[m[1]];return panes[s.match(/\[data-report-pane="(.*?)"\]/)[1]];};root.querySelectorAll=s=>s==='[data-report-pane]'?Object.values(panes):s==='[data-report-tab]'?tabs:periods;
const calls=[],pending=[],notices=[],blobs=[],links=[];let owner=true;
const c={console,Intl,Date,setTimeout:f=>f(),URL:{createObjectURL:b=>{blobs.push(b);return 'blob:test';},revokeObjectURL(){}},Blob,document:{createElement:()=>{const x=new El();links.push(x);return x;}}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(__dirname,'../play/pos/owner-reports.js'),'utf8').replace(/export /g,'')+'\nglobalThis.create=createOwnerReports;globalThis.csv=csvCell;',c);
const api=c.create({root,isOwner:()=>owner,notice:m=>notices.push(m),db:{rpc:async(name,args)=>{calls.push({name,args});return new Promise(resolve=>pending.push(resolve));}}});
const sample={generated_at:'2026-10-09T04:00:00Z',start:'2026-10-01',end:'2026-10-03',stats:{today_amount:20.90,today_orders:1,month_amount:80,month_orders:3,range_amount:20.90,range_orders:1,range_gross:25.90,range_discount:5,range_items:1},days:[{day:'2026-10-01',orders:1,amount_rm:20.90}],member_stats:{total:81},member_filtered_total:81,members:[{display_name:'<script>alert(1)</script>',phone:'+601234',points:20}],live:{pending_orders:1},reward_activity:{issued:2}};
(async()=>{els.start.value='2026-10-01';els.end.value='2026-10-03';owner=false;await api.load();assert.equal(calls.length,0);owner=true;const older=api.load();const newer=api.load();pending[1]({data:sample});await newer;pending[0]({data:{...sample,stats:{today_amount:999}}});await older;assert(panes.overview.innerHTML.includes('RM20.90'));assert(!panes.overview.innerHTML.includes('RM999.00'));assert(panes.sales.innerHTML.includes('2026-10-02'));assert(panes.sales.innerHTML.includes('RM0.00'));assert(els.memberTable.innerHTML.includes('&lt;script&gt;'));assert(!els.memberTable.innerHTML.includes('<script>'));assert(!els.next.disabled);assert(els.prev.disabled);assert.equal(calls[0].name,'yt_owner_report_v8');
 tabs.find(x=>x.dataset.reportTab==='members').click();els.export.click();const csv=await blobs.at(-1).text();assert(csv.includes("'+601234"));assert(links.at(-1).download.includes('members'));assert(links.at(-1).download.includes('page1'));assert(c.csv('=HYPERLINK("bad")').startsWith('"\'=HYPERLINK'));
 els.search.value='123';els.searchForm.onsubmit({preventDefault(){}});assert.equal(calls.at(-1).args.p_member_page,1);assert.equal(calls.at(-1).args.p_search,'123');pending.at(-1)({data:{...sample,members:[],member_filtered_total:0}});await new Promise(setImmediate);assert(els.next.disabled);
 const inflight=api.load();api.cancel();pending.at(-1)({data:{...sample,stats:{today_amount:12345}}});await inflight;assert(!panes.overview.innerHTML.includes('RM12345.00'));api.clear();assert.equal(els.memberTable.innerHTML,'');assert(els.export.disabled);console.log('PASS: report role guard, one bounded RPC, stale-response protection, zero days, escaped member names, search/page, safe CSV and logout PII clearing.');})().catch(e=>{console.error(e);process.exitCode=1;});
