const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=path.join(__dirname,'../play');
const now=Date.parse('2026-10-09T12:00:00+08:00'),day=86400000;
const c={Intl,Date:class extends Date{static now(){return now;}}};vm.createContext(c);vm.runInContext(fs.readFileSync(path.join(base,'reward-stacks.js'),'utf8').replace(/export /g,'')+'\nglobalThis.test={buildRewardStacks,rewardAvailability};',c);
function award(id,reward,days,extra={}){return {id,reward_id:reward,status:'available',redeem_after:new Date(now-day).toISOString(),expires_at:new Date(now+days*day).toISOString(),created_at:new Date(now-day).toISOString(),rewards:{name:'RM5',category:'voucher',active:true},...extra};}
const a=award('later','same',10),b=award('first','same',1),future=award('future','same',.5,{redeem_after:new Date(now+day/4).toISOString()}),expired=award('expired','same',-1),used=award('used','same',2,{status:'redeemed'}),other=award('other','other',2);
let groups=c.test.buildRewardStacks([a,expired,other,used,future,b],now);
assert.equal(groups.live.length,2);assert.equal(groups.live[0].key,'same');assert.equal(groups.live[0].items.length,3);assert.equal(groups.live[0].ready.length,2);assert.equal(groups.live[0].next.id,'first');assert.equal(groups.history.length,1);assert.equal(groups.history[0].items.length,2);
assert.equal(c.test.rewardAvailability(future,now).ready,false);assert.equal(c.test.rewardAvailability(expired,now).live,false);
const early=award('notyet','future-rule',.25,{redeem_after:new Date(now+day/8).toISOString()});groups=c.test.buildRewardStacks([early,other],now);assert.equal(groups.live[0].key,'other','ready reward ranks above earlier-expiring future reward');
const night=award('night','night',5,{rewards:{name:'Night',active:true,daily_start_local:'18:30:00',daily_end_local:'00:30:00'}});assert.equal(c.test.rewardAvailability(night,now).ready,false);assert.equal(c.test.rewardAvailability(night,Date.parse('2026-10-09T19:00:00+08:00')).ready,true);assert.equal(c.test.rewardAvailability(night,Date.parse('2026-10-10T00:00:00+08:00')).ready,true);assert.equal(c.test.rewardAvailability(night,Date.parse('2026-10-10T00:30:00+08:00')).ready,false);
const globalEnd=award('ruleEnd','ruleEnd',10,{rewards:{redeem_end_at:new Date(now-day).toISOString()}});assert.equal(c.test.rewardAvailability(globalEnd,now).live,false);
const source=fs.readFileSync(path.join(base,'app.js'),'utf8');class El{constructor(){this.children=[];this.classList={remove(){}};}append(...e){this.children.push(...e);}replaceChildren(){this.children=[];}}
const roots={walletItems:new El(),ytLoyaltyWallet:new El(),sheetBody:new El()};let opened=0,usedId,pages=[];let walletRows=Array.from({length:205},(_,i)=>award('copy'+i,'many',i+1));
const query={select(){return this;},eq(){return this;},order(){return this;},range:async(from,to)=>{pages.push(from);return {data:walletRows.slice(from,to+1)};}};
const ui={Date:class extends Date{static now(){return now;}},Intl,MY_TZ:'Asia/Kuala_Lumpur',state:{user:{id:'customer'},wallet:[],loyalty:{points_balance:99,points_history:[{direction:'earn',points:99,created_at:new Date(now).toISOString()}]}},$:id=>roots[id],document:{createElement:()=>new El()},db:{from:()=>query},unpack:r=>r.data,esc:v=>String(v),fmt:v=>String(v),updateHome(){},showSheet(){opened++;roots.sheetBody.replaceChildren();},showRewardQR:async r=>usedId=r.id,pending:(_,fn)=>fn(),copy(){},buildRewardStacks:c.test.buildRewardStacks,rewardAvailability:c.test.rewardAvailability};
vm.runInContext('globalThis.test.rewardWindow=rewardWindow;',c);ui.rewardWindow=c.test.rewardWindow;vm.createContext(ui);
vm.runInContext(source.slice(source.indexOf('async function wallet('),source.indexOf('function showSheet('))+source.slice(source.indexOf('function renderMyLoyalty('),source.indexOf('async function choosePassReward('))+'\nglobalThis.test={wallet,useNextReward,renderMyLoyalty,showPointsHistory};',ui);
(async()=>{
 await ui.test.wallet();assert.equal(ui.state.wallet.length,205);assert.equal(pages.join(','),'0,200');assert.equal(roots.walletItems.children.length,1);await ui.test.useNextReward('many');assert.equal(usedId,'copy0');
 ui.test.renderMyLoyalty();assert.equal(opened,0,'history remains closed on reward page');const actions=roots.ytLoyaltyWallet.children.find(e=>e.className==='loyalty-actions'),history=actions?.children.find(e=>e.textContent==='积分记录');assert(history);assert(!roots.ytLoyaltyWallet.children.some(e=>e.className==='yt-loyalty-history'));history.onclick();assert.equal(opened,1);assert.equal(roots.sheetBody.children[0].children.length,1);assert.equal(roots.sheetBody.children[0].children[0].children[1].textContent,'+99 P');
 console.log('PASS: identical rewards stack without merging distinct rights; usable soonest expiry wins; future/expired and daily hours respected; all pages loaded; oldest usable award selected; points history opens on demand.');
})().catch(e=>{console.error(e);process.exitCode=1;});
