const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{webcrypto}=require('node:crypto');
const root=path.join(__dirname,'..'),src=fs.readFileSync(path.join(root,'play/pos/pos.js'),'utf8');
class El{constructor(){this.value='';this.disabled=false;this.dataset={};this.children=[];this.flags=new Set();this.classList={add:k=>this.flags.add(k),remove:k=>this.flags.delete(k),toggle:(k,v)=>v?this.flags.add(k):this.flags.delete(k)};}replaceChildren(){this.children=[];}append(b){this.children.push(b);}querySelectorAll(){return this.children;}setAttribute(){} }
const e=new Proxy({},{get:(o,k)=>o[k]||(o[k]=new El())}),state={identity:null},store=new Map(),calls=[],shown=[];let quote={can_issue:true},lost=false,active=null;
const c={console,URL,Date,crypto:webcrypto,state,location:{href:'https://example.test/play/cashier/'},$:(id)=>e[id],isOwner:()=>state.identity?.can_owner,isCashier:()=>state.identity?.can_cashier,document:{createElement:()=>new El()},closeCartDrawer(){},stopRedeemCamera(){},consoleUI:null,loadAdmin:async()=>{},loadOwnerRewardOffers:async()=>{},loadBenefits:async()=>{},refreshOrders:async()=>{},showNotice(){},unpack:r=>{if(r.error)throw Error(r.error.message);return r.data;},busy:async(b,fn)=>{b.disabled=true;try{return await fn();}finally{b.disabled=false;}},sessionStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},showUnitQR:async(...args)=>shown.push(args),loadSelectedPaidUnits:async()=>{},db:{rpc:async(name,args)=>{calls.push({name,args:structuredClone(args)});if(name==='yt_pos_bundle_quote')return {data:{...quote,active_bundle:active}};if(name==='yt_pos_bundle_issue'){if(lost){lost=false;throw Error('response lost');}return {data:{id:'bundle',status:'issued',pass_count:2,expires_at:new Date(Date.now()+600000).toISOString()}};}}}};
vm.createContext(c);vm.runInContext(src.slice(src.indexOf('const defaultTab='),src.indexOf('async function loadCatalog('))+src.slice(src.indexOf('const bundleKey='),src.indexOf('async function loadSelectedPaidUnits('))+src.slice(src.indexOf('async function issueWholePass('),src.indexOf('async function issuePaidUnit('))+'\nglobalThis.test={defaultTab,buildNav,showTab,issueWholePass};',c);
(async()=>{
 for(const role of ['owner','staff','cashier']){state.identity={username:role,role,can_owner:role==='owner',can_cashier:role!=='staff'};c.test.buildNav();assert(e.nav.children.some(b=>b.dataset.tab==='benefits'));assert(!e.nav.children.some(b=>b.dataset.tab==='more'));c.test.showTab('admin');assert.equal(state.currentTab,role==='owner'?'admin':role==='cashier'?'pending':'create');c.test.showTab('history');assert.equal(state.currentTab,'history');assert(e.nav.children.find(b=>b.dataset.tab==='orders').flags.has('active'));}
 state.identity={username:'staff',role:'staff'};state.benefitOrder={order_id:'order'};e.benefitOrderSelect.value='order';e.benefitCampaign.value='campaign';e.benefitExpiry.value='10';lost=true;
 await c.test.issueWholePass(e.issueWholePass);const original=calls.find(x=>x.name==='yt_pos_bundle_issue').args;
 e.benefitCampaign.value='changed';e.benefitExpiry.value='30';await c.test.issueWholePass(e.issueWholePass);assert.deepEqual(calls.filter(x=>x.name==='yt_pos_bundle_issue').at(-1).args,original,'lost response must replay exact campaign/token/request');assert.equal(shown.at(-1)[3],'bundle');
 active={request_id:original.p_request,pass_count:2};const before=calls.filter(x=>x.name==='yt_pos_bundle_issue').length;await c.test.issueWholePass(e.issueWholePass);assert.equal(calls.filter(x=>x.name==='yt_pos_bundle_issue').length,before,'active QR is recovered without issuance');
 active={request_id:'other'};await c.test.issueWholePass(e.issueWholePass);assert.equal(calls.filter(x=>x.name==='yt_pos_bundle_issue').length,before,'other device cannot issue duplicate');
 for(const role of ['owner','staff','cashier','pos']){const html=fs.readFileSync(path.join(root,'play',role,'index.html'),'utf8');assert(html.includes('id="benefitWholeMode"'));assert(!html.includes('data-required-role'));assert(!html.includes('id="tab-more"'));}
 // Execute real login/launch with server identity, independent of the URL's Cashier alias.
 const l={...c,usable:true,restoreDraft(){},startPolling(){},buildNav:c.test.buildNav,showTab:c.test.showTab,defaultTab:c.test.defaultTab,loadCatalog:async()=>{},getBearer(){},work:async()=>({role:state.identity.role,access_token:'mock',refresh_token:'mock'}),db:{auth:{setSession:async()=>({})},rpc:async()=>({data:state.identity})}};vm.createContext(l);vm.runInContext(src.slice(src.indexOf('async function login('),src.indexOf('async function changeCashierFirstPassword('))+'\nglobalThis.login=login;',l);
 for(const role of ['owner','staff','cashier']){state.identity={username:role,role,can_owner:role==='owner',can_cashier:role!=='staff'};e.username.value=role;await l.login({preventDefault(){}});assert.equal(state.currentTab,role==='owner'?'admin':role==='cashier'?'pending':'create');}
 console.log('PASS: all roles enter via Cashier, permission routing and order tabs, Game Pass navigation, exact bundle retries and active QR recovery.');
})().catch(e=>{console.error(e);process.exitCode=1;});
